[project]
name = "task-queue"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "kush124k", email = "kushagra.24jan@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "psycopg2-binary>=2.9.12",
    "redis>=8.1.0",
    "sqlalchemy>=2.0.52",
]

[project.scripts]
task-queue = "task_queue:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
